version: "3"

services:
  redis:
    image: "redis"
    container_name: "support_redis"
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    container_name: "nginx_server" 
    ports:
      - "1300:80"
    depends_on:
      - app
    restart: "on-failure"
    volumes:
      - "static_volume:/app/staticfiles/"
        
  postgres:
    image: "postgres:14"
    container_name: "support_db"
    env_file: ".env"
    ports:
       - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  app: 
    stdin_open: true 
    tty: true
    build: 
      context: . 
      dockerfile: "Dockerfile" 
    command: "gunicorn src.config.wsgi -c gunicorn.conf.py"
    image: "support_app"
    container_name: "support_app" 
    env_file: ".env" 
    depends_on:
      - "postgres" 
    volumes:
      - ".:/app/"
      - "static_volume:/app/staticfiles/" 
    ports:
      - "8000"

volumes:
  pg_data: {} 
  static_volume: {}
