version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    environment:
      - PIPENV_VENV_IN_PROJECT=1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              postgresql-client \
              gettext \
              libpq-dev \
              build-essential \
              python3-dev
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            - v1-dependencies-
      - run:
          name: Install Python dependencies
          command: |
            pip install --user pipenv
            pipenv install --dev --system --deploy
      - save_cache:
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local/share/virtualenvs/
      - run:
          name: Lint code
          command: |
            pipenv run flake8 .
            pipenv run mypy .
            pipenv run isort --check-only --diff .
            pipenv run black --check .