version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  check-code-quality:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Run linter
          command: pipenv run flake8 .
      - run:
          name: Check formatting
          command: pipenv run black --check . && pipenv run isort --check-only .
      - run:
          name: Check static types
          command: pipenv run mypy .
  run-linter:
         

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - check-code-quality
      - hold-deploy:
          type: approval
          requires:
            - check-code-quality
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold-deploy
          filters:
            branches:
              only: master
